Module SCDBModule
    Public Function ToScdbeps() As String
        Dim strbulider As New System.Text.StringBuilder


        strbulider.AppendLine("import tempcustomText as tct;")
        strbulider.AppendLine("import TriggerEditor as te;")
        strbulider.AppendLine("")
        strbulider.AppendLine("var customMessage = 0;")
        strbulider.AppendLine("const ChecksumValue = EUDArray(list(0xABCDEFED, 0xCBABACDE));")

        strbulider.AppendLine("const Connect = EUDArray(8);")
        strbulider.AppendLine("const Datapage = EUDArray(8);")
        strbulider.AppendLine("const Respons = EUDArray(8);")
        strbulider.AppendLine("const Ping = EUDArray(8);")
        strbulider.AppendLine("const Status = EUDArray(8);")
        strbulider.AppendLine("const LastDatapage = EUDArray(8);")
        strbulider.AppendLine("const CheckSum = EUDArray(8);")
        strbulider.AppendLine("const DataChunkCount = EUDArray(8);")
        strbulider.AppendLine("const SaveTimer = EUDArray(8);")
        strbulider.AppendLine("const LoadTimer = EUDArray(8);")
        strbulider.AppendLine("const LastStatus = EUDArray(8);")
        strbulider.AppendLine("const isSaveStart = EUDArray(8);")
        strbulider.AppendLine("const isLoadStart = EUDArray(8);")
        strbulider.AppendLine("")
        strbulider.AppendLine("const mainAddress = 5829924;")
        strbulider.AppendLine("const mainAddressEPD = EPD(5829924);")
        strbulider.AppendLine("")
        strbulider.AppendLine("const DataArrayLength = 4096;")
        strbulider.AppendLine("const DataArray = EUDArray(DataArrayLength * 8);")
        strbulider.AppendLine("")
        strbulider.AppendLine("var playerCode = 0;")
        strbulider.AppendLine("var DataCount = 0;")


        Dim crc32 As New CRC32


        crc32.GetCRC32(SCDBMapName)






        strbulider.AppendLine("const mapCode = 0x" & Hex(crc32.GetCRC32(SCDBMapName)) & ";")
        strbulider.AppendLine("const MakerCode = 0x" & Hex(crc32.GetCRC32(SCDBMaker)) & ";")
        strbulider.AppendLine("")
        strbulider.AppendLine("const DataSize = " & SCDBDataSize & ";")
        strbulider.AppendLine("const Datas = EUDArray(DataSize * 8);")
        strbulider.AppendLine("")
        strbulider.AppendLine("const VariableCount = " & SCDBVariable.Count & ";")
        strbulider.AppendLine("")
        strbulider.AppendLine("const UnitIndexCount = " & SCDBDeath.Count & ";")


        Dim tstr As String = ""

        For i = 0 To SCDBDeath.Count - 1
            If i = 0 Then
                tstr = SCDBDeath(i)
            Else
                tstr = tstr & ", " & SCDBDeath(i)
            End If
        Next
        If SCDBDeath.Count = 0 Then
            tstr = 0
        End If


        strbulider.AppendLine("const UnitIndex = EUDArray(list(" & tstr & "));")
        strbulider.AppendLine("")
        strbulider.AppendLine("const LocationCount = " & SCDBLoc.Count & ";")



        For i = 0 To SCDBLoc.Count - 1
            If i = 0 Then
                tstr = SCDBLoc(i) - 1
            Else
                tstr = tstr & ", " & SCDBLoc(i) - 1
            End If
        Next
        If SCDBLoc.Count = 0 Then
            tstr = 0
        End If
        strbulider.AppendLine("const LocationSaveIndex = EUDArray(list(" & tstr & "));")


        For i = 0 To SCDBLocLoad.Count - 1
            If i = 0 Then
                tstr = SCDBLocLoad(i) - 1
            Else
                tstr = tstr & ", " & SCDBLocLoad(i) - 1
            End If
        Next
        If SCDBLocLoad.Count = 0 Then
            tstr = 0
        End If

        strbulider.AppendLine("const LocationIndex = EUDArray(list(" & tstr & "));")
        strbulider.AppendLine("")
        strbulider.AppendLine("const DeathsAddress = ((3 + DataSize) / 12) * 12;")
        strbulider.AppendLine("")


        strbulider.AppendLine("function Init() {")
        strbulider.AppendLine("    const checksum = ChecksumValue[0];")
        strbulider.AppendLine("    // SetMemoryEPD(mainAddressEPD - 2, SetTo, checksum);")
        strbulider.AppendLine("    VProc(checksum, checksum.SetDest(mainAddressEPD - 2));")
        strbulider.AppendLine("}")



        'strbulider.AppendLine("//Status = 0 연결 끊킴")
        'strbulider.AppendLine("//            1 연결 됨, 대기중")
        'strbulider.AppendLine("//            2 연결 중")
        'strbulider.AppendLine("//            3 연결 중 로드")
        'strbulider.AppendLine("//            4 연결 중 세이브")
        'strbulider.AppendLine("//            5 세이브 중")
        'strbulider.AppendLine("//            6 로드 중")
        'strbulider.AppendLine("")
        'strbulider.AppendLine("//Connect = 0 연결 끊킴")
        'strbulider.AppendLine("//               1 연결됨(데이터없음)")
        'strbulider.AppendLine("//               2 연결됨(데이터있음)")
        'strbulider.AppendLine("//               3 저장 중")
        'strbulider.AppendLine("//               4 로드 중")
        strbulider.AppendLine("function GetStatus() {")
        strbulider.AppendLine("    return Status[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetLastMsg() {")
        strbulider.AppendLine("    return LastStatus[getcurpl()];")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function msgReset() {")
        strbulider.AppendLine("    LastStatus[getcurpl()] = 0;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function UseCustomMsg(Use) {")
        strbulider.AppendLine("    customMessage = Use;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetPlayerCode();")
        strbulider.AppendLine("function count_at_loc(player, units, loc);")
        strbulider.AppendLine("function SCDBExec();")
        strbulider.AppendLine("function SetIndexedValue(Vindex, Value);")
        strbulider.AppendLine("function GetIndexedValue(Vindex);")
        strbulider.AppendLine("function QCOff();")
        strbulider.AppendLine("function QCOn();")
        strbulider.AppendLine("function ReadPacket();")
        strbulider.AppendLine("function ReadData();")
        strbulider.AppendLine("function WriteData();")
        strbulider.AppendLine("function WriteConnect(Value);")
        strbulider.AppendLine("function WriteDatapage(Value);")
        strbulider.AppendLine("function WriteRespons(Value);")
        strbulider.AppendLine("function WriteChecksum(Value);")
        strbulider.AppendLine("function LoadStart();")
        strbulider.AppendLine("function LoadExec();")
        strbulider.AppendLine("function SaveDataLoad();")
        strbulider.AppendLine("function SaveStart();")
        strbulider.AppendLine("function SaveExec();")
        strbulider.AppendLine("function Login();")
        strbulider.AppendLine("function LoginExec();")
        strbulider.AppendLine("function GetPlayerCode() {")
        strbulider.AppendLine("    if (IsUserCP()) {")
        strbulider.AppendLine("        const cp = getuserplayerid();")
        strbulider.AppendLine("        const dst = EPD(0x57EEE8) + 9 * cp;")
        strbulider.AppendLine("        var Value = dwread_epd(dst) / 0x1000000;")
        strbulider.AppendLine("        for(var i = 1 ; i < 7 ; i++) {")
        strbulider.AppendLine("            Value += dwread_epd(dst + i);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        playerCode = Value;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function count_at_loc(player ,units ,loc) {")
        strbulider.AppendLine("    var x = 2047;")
        strbulider.AppendLine("    foreach(i : py_range(10, -1, -1)) {")
        strbulider.AppendLine("        if (x >= py_pow(2, i)) {")
        strbulider.AppendLine("            x -= py_pow(2, i);")
        strbulider.AppendLine("            if (!Bring(player, AtMost, x, units, loc+1)) {")
        strbulider.AppendLine("                x += py_pow(2, i);")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    return x;")
        strbulider.AppendLine("    //made by Artanis[M] & safhfh & Jpoker & trgk;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SCDBExec() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    dwsubtract_epd(EPD(SaveTimer) + cp, 1);")
        strbulider.AppendLine("    dwsubtract_epd(EPD(LoadTimer) + cp, 1);")
        strbulider.AppendLine("    if (Status[cp] == 5 && SaveTimer[cp] == 0) {")
        strbulider.AppendLine("        SaveExec();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Status[cp] == 6 && LoadTimer[cp] == 0) {")
        strbulider.AppendLine("        LoadExec();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Status[cp] >= 2 && Status[cp] <= 4) {")
        strbulider.AppendLine("        LoginExec();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (isSaveStart[cp] == 1) {")
        strbulider.AppendLine("        SaveStart();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (isLoadStart[cp] == 1) {")
        strbulider.AppendLine("        LoadStart();")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SetIndexedValue(Vindex ,Value) {")
        strbulider.AppendLine("    switch(Vindex) {")

        For i = 0 To SCDBVariable.Count - 1

            strbulider.AppendLine("        case " & i & ":")
            strbulider.AppendLine("            te." & SCDBVariable(i) & " = Value;")
            strbulider.AppendLine("        break;")

        Next




        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function GetIndexedValue(Vindex) {")
        strbulider.AppendLine("    switch(Vindex) {")
        For i = 0 To SCDBVariable.Count - 1

            strbulider.AppendLine("        case " & i & ":")
            strbulider.AppendLine("            return te." & SCDBVariable(i) & ";")
            strbulider.AppendLine("        break;")

        Next
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    return 0;")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function QCOff() {")
        strbulider.AppendLine("    Trigger(IsUserCP(), SetMemoryEPD(mainAddressEPD - 1, SetTo, 0));")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function QCOn() {")
        strbulider.AppendLine("    Trigger(IsUserCP(), SetMemoryEPD(mainAddressEPD - 1, SetTo, 1));")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadPacket() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    SetMemory(0x6509B0, Add, mainAddressEPD + 12 * 1 + DeathsAddress);")
        strbulider.AppendLine("    if (Deaths(CurrentPlayer, AtLeast, 1, 0)) {")
        strbulider.AppendLine("        const tConnect = dwread_cp(0);")
        strbulider.AppendLine("        Connect[cp] = tConnect - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Deaths(CurrentPlayer, AtLeast, 1, 1)) {")
        strbulider.AppendLine("        SetMemory(0x6509B0, Add, 12 * 1);")
        strbulider.AppendLine("        const tDatapage = dwread_cp(0);")
        strbulider.AppendLine("        Datapage[cp] = tDatapage - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Deaths(CurrentPlayer, AtLeast, 1, 2)) {")
        strbulider.AppendLine("        SetMemory(0x6509B0, Add, 12 * 2);")
        strbulider.AppendLine("        const tRespons = dwread_cp(0);")
        strbulider.AppendLine("        Respons[cp] = tRespons - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Deaths(CurrentPlayer, AtLeast, 1, 3)) {")
        strbulider.AppendLine("        SetMemory(0x6509B0, Add, 12 * 3);")
        strbulider.AppendLine("        const tChecksum = dwread_cp(0);")
        strbulider.AppendLine("        CheckSum[cp] = tChecksum - 1;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    setcurpl2cpcache();")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function ReadData() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    var tCheckSum = 0;")
        strbulider.AppendLine("    var dst = mainAddressEPD + 12 * 5 + DeathsAddress + cp;")
        strbulider.AppendLine("    var index = DataSize * cp;")
        strbulider.AppendLine("    for(var i = 0 ; i < DataSize ; SetVariables(list(i, index, dst), list(1, 1, 12), list(Add, Add, Add))) {")
        strbulider.AppendLine("        Datas[index] = dwread_epd(dst);")
        strbulider.AppendLine("        tCheckSum += Datas[index];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    tCheckSum = tCheckSum % 1000000;")
        strbulider.AppendLine("    return l2v(tCheckSum == CheckSum[cp]);")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteData() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    var tCheckSum = 0;")
        strbulider.AppendLine("    var index = DataSize * cp;")
        strbulider.AppendLine("    for(var i = 0 ; i < DataSize ; SetVariables(list(i, index), list(1, 1), list(Add, Add))) {")
        strbulider.AppendLine("        if (IsUserCP()) {")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 4 + i, SetTo, Datas[index]);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        tCheckSum += Datas[index];")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    tCheckSum = tCheckSum % 1000000;")
        strbulider.AppendLine("    WriteChecksum(tCheckSum);")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteConnect(Value) {")
        strbulider.AppendLine("    if (IsUserCP()) { VProc(Value, list(Value.SetDest(mainAddressEPD), Value.AddNumber(1))); }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteDatapage(Value) {")
        strbulider.AppendLine("    if (IsUserCP()) { VProc(Value, list(Value.SetDest(mainAddressEPD + 1), Value.AddNumber(1))); }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteRespons(Value) {")
        strbulider.AppendLine("    if (IsUserCP()) { VProc(Value, list(Value.SetDest(mainAddressEPD + 2), Value.AddNumber(1))); }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function WriteChecksum(Value) {")
        strbulider.AppendLine("    if (IsUserCP()) { VProc(Value, list(Value.SetDest(mainAddressEPD + 3), Value.AddNumber(1))); }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadStart() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    if (LoadTimer[cp] == 0) {")
        strbulider.AppendLine("        epdswitch(EPD(Status) + cp) {")
        strbulider.AppendLine("            case 0:")
        strbulider.AppendLine("                Status[cp] = 3;")
        strbulider.AppendLine("                LastStatus[cp] = 3;")
        strbulider.AppendLine("                Login();")
        strbulider.AppendLine("            break;")
        strbulider.AppendLine("            case 1:")
        strbulider.AppendLine("                QCOn();")
        strbulider.AppendLine("                ReadPacket();")
        strbulider.AppendLine("                if (Connect[cp] == 1) {")
        strbulider.AppendLine("                    Status[cp] = 1;")
        strbulider.AppendLine("                    LastStatus[cp] = 2;")
        strbulider.AppendLine("                    if (customMessage == 0) {")
        strbulider.AppendLine("                        PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x08데이터 파일\x04이 없습니다."");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    isLoadStart[cp] = 0;")
        strbulider.AppendLine("                    QCOff();")
        strbulider.AppendLine("                } else if (Connect[cp] == 2) {")
        strbulider.AppendLine("                    isLoadStart[cp] = 0;")
        strbulider.AppendLine("                    WriteConnect(4);")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                    Status[cp] = 6;")
        strbulider.AppendLine("                    LastStatus[cp] = 6;")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            break;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoadExec() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    ReadPacket();")
        strbulider.AppendLine("    LastStatus[cp] = 4;")
        strbulider.AppendLine("    if (customMessage == 0) {")
        strbulider.AppendLine("        tct.chatAnnouncement(""\x03데이터\x04를 \x07불러오는 중"");")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Datapage[cp] >= 999999) {")
        strbulider.AppendLine("        LoadTimer[cp] = 60;")
        strbulider.AppendLine("        Ping[cp] = 0;")
        strbulider.AppendLine("        Status[cp] = 1;")
        strbulider.AppendLine("        LastStatus[cp] = 5;")
        strbulider.AppendLine("        Datapage[cp] = 0;")
        strbulider.AppendLine("        WriteConnect(2);")
        strbulider.AppendLine("        WriteRespons(0);")
        strbulider.AppendLine("        WriteDatapage(0);")
        strbulider.AppendLine("        QCOff();")
        strbulider.AppendLine("        if (customMessage == 0) {")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\tdrtra00.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x03데이터\x04를 \x07성공적으로 불러왔습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        const lastPage = (LastDatapage[cp] - 1) * DataSize;")
        strbulider.AppendLine("        var dataEPD = EPD(DataArray) + cp * DataArrayLength;")
        strbulider.AppendLine("        for(var i = 0 ; i < lastPage ; SetVariables(list(i, dataEPD), list(1, 1), list(Add, Add))) {")
        strbulider.AppendLine("            if (!MemoryEPD(dataEPD, Exactly, 999999)) {")
        strbulider.AppendLine("                var tDataValue = dwread_epd(dataEPD);")
        strbulider.AppendLine("                if (tDataValue < 100000) {")
        strbulider.AppendLine("                    const index, value = div(tDataValue, 1000);")
        strbulider.AppendLine("                    SetIndexedValue(index, value);")
        strbulider.AppendLine("                } else if (tDataValue < 200000) {")
        strbulider.AppendLine("                    const index, value = div(tDataValue, 1000);")
        strbulider.AppendLine("                    SetVariables(list(i, dataEPD), list(1, 1), list(Add, Add));")
        strbulider.AppendLine("                    SetIndexedValue(index - 100, value * 1000000 + dwread_epd(dataEPD));")
        strbulider.AppendLine("                } else if (tDataValue < 300000) {")
        strbulider.AppendLine("                    const index = tDataValue / 1000 - 200;")
        strbulider.AppendLine("                    SetVariables(list(i, dataEPD), list(2, 1), list(Add, Add));")
        strbulider.AppendLine("                    var tValue = dwread_epd(dataEPD) * 1000000;")
        strbulider.AppendLine("                    dataEPD += 1;")
        strbulider.AppendLine("                    SetIndexedValue(index, tValue + dwread_epd(dataEPD));")
        strbulider.AppendLine("                } else if (tDataValue < 400000) {")
        strbulider.AppendLine("                    const index, value = div(tDataValue, 1000);")
        strbulider.AppendLine("                    CreateUnit(1, value, LocationIndex[index - 300] + 1, CurrentPlayer);")
        strbulider.AppendLine("                } else if (tDataValue < 500000) {")
        strbulider.AppendLine("                    const index = LocationIndex[tDataValue / 1000 - 400] + 1;")
        strbulider.AppendLine("                    SetVariables(list(i, dataEPD), list(1, 1), list(Add, Add));")
        strbulider.AppendLine("                    const UnitNum, value = div(dwread_epd(dataEPD), 1000);")
        strbulider.AppendLine("                    CreateUnit(value, UnitNum, index, CurrentPlayer);")
        strbulider.AppendLine("                } else if (tDataValue < 600000) {")
        strbulider.AppendLine("                    const index, value = div(tDataValue, 1000);")
        strbulider.AppendLine("                    SetDeaths(CurrentPlayer, SetTo, value, UnitIndex[index - 500]);")
        strbulider.AppendLine("                } else if (tDataValue < 700000) {")
        strbulider.AppendLine("                    const index, value = div(tDataValue, 1000);")
        strbulider.AppendLine("                    SetVariables(list(i, dataEPD), list(1, 1), list(Add, Add));")
        strbulider.AppendLine("                    SetDeaths(CurrentPlayer, SetTo, value * 1000000 + dwread_epd(dataEPD), UnitIndex[index - 600]);")
        strbulider.AppendLine("                } else if (tDataValue < 800000) {")
        strbulider.AppendLine("                    const index = UnitIndex[tDataValue / 1000 - 700];")
        strbulider.AppendLine("                    SetVariables(list(i, dataEPD), list(2, 1), list(Add, Add));")
        strbulider.AppendLine("                    const value = dwread_epd(dataEPD) * 1000000;")
        strbulider.AppendLine("                    dataEPD += 1;")
        strbulider.AppendLine("                    SetDeaths(CurrentPlayer, SetTo, value + dwread_epd(dataEPD), index);")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        return;")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Respons[cp] == 1 && ReadData()) {")
        strbulider.AppendLine("        Ping[cp] = 0;")
        strbulider.AppendLine("        const myPage = Datapage[cp];")
        strbulider.AppendLine("        var index1, index2 = (myPage - 2) * DataSize + DataArrayLength * cp, DataSize * cp;")
        strbulider.AppendLine("        for(var i = 0 ; i < DataSize ; SetVariables(list(i, index1, index2), list(1, 1, 1), list(Add, Add, Add))) {")
        strbulider.AppendLine("            DataArray[index1] = Datas[index2];")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if (LastDatapage[cp] != myPage) {")
        strbulider.AppendLine("            LastDatapage[cp] = myPage;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        WriteRespons(2);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    Ping[cp] += 1;")
        strbulider.AppendLine("    if (Ping[cp] >= 100) {")
        strbulider.AppendLine("        Connect[cp] = 0;")
        strbulider.AppendLine("        Status[cp] = 0;")
        strbulider.AppendLine("        LastStatus[cp] = 8;")
        strbulider.AppendLine("        if (customMessage == 0) {")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처와 연결이 끊어졌습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        const inits = list(SetMemoryEPD(mainAddressEPD - 1, SetTo, 0));")
        strbulider.AppendLine("        foreach(n : py_range(8)) {")
        strbulider.AppendLine("            inits.append(SetMemoryEPD(mainAddressEPD + n, SetTo, 1));")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        Trigger(IsUserCP(), inits);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveDataLoad() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    const indexOffset = cp * DataArrayLength;")
        strbulider.AppendLine("    var Index = indexOffset;")
        strbulider.AppendLine("    for(var i, i1000 = 0, 0 ; i < VariableCount ; SetVariables(list(i, i1000), list(1, 1000), list(Add, Add))) {")
        strbulider.AppendLine("        var tValue = GetIndexedValue(i);")
        strbulider.AppendLine("        if (tValue <= 999) {")
        strbulider.AppendLine("            DataArray[Index] = tValue + i1000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        } else if (tValue <= 999999999) {")
        strbulider.AppendLine("            const q, r = div(tValue, 1000000);")
        strbulider.AppendLine("            DataArray[Index] = q + i1000 + 100000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("            DataArray[Index] = r;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        } else {")
        strbulider.AppendLine("            DataArray[Index] = i1000 + 200000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("            const q, r = div(tValue, 1000000);")
        strbulider.AppendLine("            DataArray[Index] = q % 1000000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("            DataArray[Index] = r;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    for(var i, i1000 = 0, 0 ; i < UnitIndexCount ; SetVariables(list(i, i1000), list(1, 1000), list(Add, Add))) {")
        strbulider.AppendLine("        var tValue = dwread_epd(12 * UnitIndex[i] + cp);")
        strbulider.AppendLine("        if (tValue <= 999) {")
        strbulider.AppendLine("            DataArray[Index] = tValue + i1000 + 500000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        } else if (tValue <= 999999999) {")
        strbulider.AppendLine("            const q, r = div(tValue, 1000000);")
        strbulider.AppendLine("            DataArray[Index] = q + i1000 + 600000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("            DataArray[Index] = r;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        } else {")
        strbulider.AppendLine("            DataArray[Index] = i1000 + 700000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("            DataArray[Index] = q % 1000000;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("            DataArray[Index] = r;")
        strbulider.AppendLine("            Index += 1;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    const unitCountWrite = function (count, j, j1000) {")
        strbulider.AppendLine("        if (count >= 1) {")
        strbulider.AppendLine("            if (count == 1) {")
        strbulider.AppendLine("                DataArray[Index] = i1000 + j + 300000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("            } else {")
        strbulider.AppendLine("                DataArray[Index] = i1000 + 400000;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("                DataArray[Index] = j1000 + count;")
        strbulider.AppendLine("                Index += 1;")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    };")
        strbulider.AppendLine("    for(var i, i1000 = 0, 0 ; i < LocationCount ; SetVariables(list(i, i1000), list(1, 1000), list(Add, Add))) {")
        strbulider.AppendLine("        const loc = LocationSaveIndex[i];")
        strbulider.AppendLine("        for(var j, j4, j4000 = 0 ; j4 < 228 / 4 ; SetVariables(list(j, j4, j4000), list(4, 1, 4000), list(Add, Add, Add))) {")
        strbulider.AppendLine("            const epd = EPD(0x6637A0) + j4;")
        strbulider.AppendLine("            foreach(n : py_range(4)) {")
        strbulider.AppendLine("                if (MemoryXEPD(epd, AtLeast, 1, 8 << (n * 8))) {")
        strbulider.AppendLine("                    unitCountWrite(count_at_loc(cp, j + n, loc), j + n, j4000 + 1000 * n);")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    DataChunkCount[cp] = Index - indexOffset;")
        strbulider.AppendLine("    /*테스트")
        strbulider.AppendLine("    DataArray[0] = 300037;")
        strbulider.AppendLine("    DataArray[1] = 300038;")
        strbulider.AppendLine("    DataArray[2] = 300039;")
        strbulider.AppendLine("    DataArray[3] = 300040;")
        strbulider.AppendLine("    DataArray[4] = 300041;")
        strbulider.AppendLine("    DataArray[5] = 300042;")
        strbulider.AppendLine("    DataArray[6] = 300043;")
        strbulider.AppendLine("    DataArray[7] = 300044;")
        strbulider.AppendLine("    DataArray[8] = 300045;")
        strbulider.AppendLine("    DataChunkCount[cp] = 9;")
        strbulider.AppendLine("    */")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveStart() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    if (SaveTimer[cp] == 0) {")
        strbulider.AppendLine("        switch(Status[cp]) {")
        strbulider.AppendLine("            case 0:")
        strbulider.AppendLine("                Status[cp] = 4;")
        strbulider.AppendLine("                LastStatus[cp] = 4;")
        strbulider.AppendLine("                Login();")
        strbulider.AppendLine("            break;")
        strbulider.AppendLine("            case 1:")
        strbulider.AppendLine("                Ping[cp] += 1;")
        strbulider.AppendLine("                QCOn();")
        strbulider.AppendLine("                ReadPacket();")
        strbulider.AppendLine("                if (Datapage[cp] == 0")
        strbulider.AppendLine("                    && Connect[cp] >= 1 && Connect[cp] <= 2")
        strbulider.AppendLine("                ) {")
        strbulider.AppendLine("                    isSaveStart[cp] = 0;")
        strbulider.AppendLine("                    Ping[cp] = 0;")
        strbulider.AppendLine("                    WriteConnect(3);")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                    SaveDataLoad();")
        strbulider.AppendLine("                    Status[cp] = 5;")
        strbulider.AppendLine("                    LastStatus[cp] = 6;")
        strbulider.AppendLine("                } else {")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("                if (Ping[cp] >= 100) {")
        strbulider.AppendLine("                    Connect[cp] = 0;")
        strbulider.AppendLine("                    Status[cp] = 0;")
        strbulider.AppendLine("                    LastStatus[cp] = 8;")
        strbulider.AppendLine("                    isSaveStart[cp] = 0;")
        strbulider.AppendLine("                    if (customMessage == 0) {")
        strbulider.AppendLine("                        PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x08런처와 연결이 끊어졌습니다."");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                    if (IsUserCP()) {")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD - 1, SetTo, 0);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 1, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 2, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 3, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 4, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 5, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 6, SetTo, 1);")
        strbulider.AppendLine("                        SetMemoryEPD(mainAddressEPD + 7, SetTo, 1);")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            break;")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function SaveExec() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    ReadPacket();")
        strbulider.AppendLine("    LastStatus[cp] = 6;")
        strbulider.AppendLine("    if (customMessage == 0) {")
        strbulider.AppendLine("        tct.chatAnnouncement(""\x07데이터\x04를 \x1F저장하는 중..."");")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    if (Respons[cp] == 1) {")
        strbulider.AppendLine("        Ping[cp] = 0;")
        strbulider.AppendLine("        for(var i = 0 ; i < DataSize ; i++) {")
        strbulider.AppendLine("            if (DataChunkCount[cp] <= i + DataSize * (Datapage[cp] - 1)) {")
        strbulider.AppendLine("                Datas[i + cp * DataSize] = 999999;")
        strbulider.AppendLine("            } else {")
        strbulider.AppendLine("                Datas[i + cp * DataSize] = DataArray[i + DataSize * (Datapage[cp] - 1) + cp * DataArrayLength];")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        WriteData();")
        strbulider.AppendLine("        if (DataChunkCount[cp] <= DataSize * (Datapage[cp] - 1)) {")
        strbulider.AppendLine("            WriteRespons(3);")
        strbulider.AppendLine("            Status[cp] = 1;")
        strbulider.AppendLine("            LastStatus[cp] = 7;")
        strbulider.AppendLine("            Respons[cp] = 0;")
        strbulider.AppendLine("            Connect[cp] = 2;")
        strbulider.AppendLine("            QCOff();")
        strbulider.AppendLine("            SaveTimer[cp] = 60;")
        strbulider.AppendLine("            if (customMessage == 0) {")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\tdrtra00.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x03데이터\x04를 \x1F성공적으로 저장했습니다."");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        } else {")
        strbulider.AppendLine("            if (ReadData()) {")
        strbulider.AppendLine("                WriteRespons(2);")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    Ping[cp] += 1;")
        strbulider.AppendLine("    if (Ping[cp] >= 100) {")
        strbulider.AppendLine("        Connect[cp] = 0;")
        strbulider.AppendLine("        Status[cp] = 0;")
        strbulider.AppendLine("        LastStatus[cp] = 8;")
        strbulider.AppendLine("        if (customMessage == 0) {")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처와 연결이 끊어졌습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if (IsUserCP()) {")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD - 1, SetTo, 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 1, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 2, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 3, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 4, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 5, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 6, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 7, SetTo, 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function Login() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    Ping[cp] = 0;")
        strbulider.AppendLine("    if (IsUserCP()) {")
        strbulider.AppendLine("        GetPlayerCode();")
        strbulider.AppendLine("        DataCount = VariableCount + UnitIndexCount + LocationCount;")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD - 1, SetTo, 1);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD, SetTo, 0x12348765);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 1, SetTo, 0x9ABCF1DE);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 2, SetTo, 0x23458967);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 3, SetTo, mapCode);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 4, SetTo, MakerCode);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 5, SetTo, playerCode);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 6, SetTo, DataCount);")
        strbulider.AppendLine("        SetMemoryEPD(mainAddressEPD + 7, SetTo, DataSize);")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("}")
        strbulider.AppendLine("function LoginExec() {")
        strbulider.AppendLine("    const cp = getcurpl();")
        strbulider.AppendLine("    LastStatus[cp] = 1;")
        strbulider.AppendLine("    if (customMessage == 0) {")
        strbulider.AppendLine("        tct.chatAnnouncement(""\x07런처\x04의 응답을 \x03기다리는 중 입니다.\x04... \x05"", Ping[cp], """");")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    ReadPacket();")

        strbulider.AppendLine("    if (Ping[cp] >= 50) {")
        strbulider.AppendLine("        if (Status[cp] == 4")
        strbulider.AppendLine("            && Connect[cp] >= 1 && Connect[cp] <= 2")
        strbulider.AppendLine("        ) {")
        strbulider.AppendLine("            SaveDataLoad();")
        strbulider.AppendLine("            WriteConnect(3);")
        strbulider.AppendLine("            SaveDataLoad();")
        strbulider.AppendLine("            Ping[cp] = 0;")
        strbulider.AppendLine("            Status[cp] = 5;")
        strbulider.AppendLine("            LastStatus[cp] = 3;")
        strbulider.AppendLine("            SaveTimer[cp] = 60;")
        strbulider.AppendLine("            isSaveStart[cp] = 0;")
        strbulider.AppendLine("            if (customMessage == 0) {")
        strbulider.AppendLine("                PlayWAV(""sound\\misc\\trescue.wav"");")
        strbulider.AppendLine("                tct.chatAnnouncement(""\x07런처\x04와 \x03연결되었습니다."");")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        } else {")
        strbulider.AppendLine("            if (Status[cp] == 3) {")
        strbulider.AppendLine("                if (Connect[cp] == 2) {")
        strbulider.AppendLine("                    WriteConnect(4);")
        strbulider.AppendLine("                    WriteDatapage(0);")
        strbulider.AppendLine("                    Ping[cp] = 0;")
        strbulider.AppendLine("                    Status[cp] = 6;")
        strbulider.AppendLine("                    LastStatus[cp] = 3;")
        strbulider.AppendLine("                    LoadTimer[cp] = 60;")
        strbulider.AppendLine("                    isLoadStart[cp] = 0;")
        strbulider.AppendLine("                    if (customMessage == 0) {")
        strbulider.AppendLine("                        PlayWAV(""sound\\misc\\trescue.wav"");")
        strbulider.AppendLine("                        tct.chatAnnouncement(""\x07런처\x04와 \x03연결되었습니다."");")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                } else {")
        strbulider.AppendLine("                    if (Connect[cp] == 1) {")
        strbulider.AppendLine("                        isLoadStart[cp] = 0;")
        strbulider.AppendLine("                        Ping[cp] = 0;")
        strbulider.AppendLine("                        Status[cp] = 1;")
        strbulider.AppendLine("                        LastStatus[cp] = 2;")
        strbulider.AppendLine("                        if (customMessage == 0) {")
        strbulider.AppendLine("                            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("                            tct.chatAnnouncement(""\x08데이터 파일\x04이 없습니다."");")
        strbulider.AppendLine("                        }")
        strbulider.AppendLine("                        QCOff();")
        strbulider.AppendLine("                    }")
        strbulider.AppendLine("                }")
        strbulider.AppendLine("            }")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    Ping[cp] += 1;")
        strbulider.AppendLine("    if (Ping[cp] >= 200) {")
        strbulider.AppendLine("        Connect[cp] = 0;")
        strbulider.AppendLine("        Status[cp] = 0;")
        strbulider.AppendLine("        LastStatus[cp] = 9;")
        strbulider.AppendLine("        isLoadStart[cp] = 0;")
        strbulider.AppendLine("        isSaveStart[cp] = 0;")
        strbulider.AppendLine("        if (customMessage == 0) {")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처를 확인하지 못했습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if (IsUserCP()) {")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD - 1, SetTo, 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 1, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 2, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 3, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 4, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 5, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 6, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 7, SetTo, 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    }")
        strbulider.AppendLine("    var tCheckLogout = dwread_epd(mainAddressEPD + 12 * 8 + cp + DeathsAddress);")
        strbulider.AppendLine("    if (tCheckLogout == 999998) {")
        strbulider.AppendLine("        Connect[cp] = 0;")
        strbulider.AppendLine("        Status[cp] = 0;")
        strbulider.AppendLine("        LastStatus[cp] = 9;")
        strbulider.AppendLine("        isLoadStart[cp] = 0;")
        strbulider.AppendLine("        isSaveStart[cp] = 0;")
        strbulider.AppendLine("        if (customMessage == 0) {")
        strbulider.AppendLine("            PlayWAV(""sound\\misc\\outofgas.wav"");")
        strbulider.AppendLine("            tct.chatAnnouncement(""\x08런처가 연결을 강제로 끊었습니다."");")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("        if (IsUserCP()) {")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD - 1, SetTo, 0);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 1, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 2, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 3, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 4, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 5, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 6, SetTo, 1);")
        strbulider.AppendLine("            SetMemoryEPD(mainAddressEPD + 7, SetTo, 1);")
        strbulider.AppendLine("        }")
        strbulider.AppendLine("    } else if ( tCheckLogout == 1000000) { Defeat(); }")
        strbulider.AppendLine("}")

        Return strbulider.ToString
    End Function
End Module
